resolver:  nightly-2017-08-25
# resolver: lts-9.1

packages:
- .

extra-deps: []

flags: {}

extra-package-dbs: []

# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# compiler-check: newer-minor
